# Generated by Django 5.1.5 on 2025-02-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
