# Generated by Django 5.1.5 on 2025-02-12 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_calendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='date',
            field=models.DateTimeField(default='2024-01-01'),
            preserve_default=False,
        ),
    ]
