# Generated by Django 5.1.5 on 2025-02-15 23:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_calendar_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('get_date', models.DateField(verbose_name='取得日')),
                ('label', models.PositiveSmallIntegerField(choices=[(1, 'クロス'), (2, '現渡'), (4, '株主書類のみ'), (5, '優待到着'), (9, 'その他')], verbose_name='ラベル')),
                ('code', models.CharField(max_length=4, verbose_name='銘柄コード')),
                ('stock_name', models.CharField(max_length=100, verbose_name='銘柄名')),
                ('get_month', models.PositiveSmallIntegerField(choices=[(1, '1月'), (2, '2月'), (3, '3月'), (4, '4月'), (5, '5月'), (6, '6月'), (7, '7月'), (8, '8月'), (9, '9月'), (10, '10月'), (11, '11月'), (12, '12月')], verbose_name='優待月')),
                ('stock_price', models.IntegerField(verbose_name='株価')),
                ('fee', models.IntegerField(verbose_name='手数料')),
                ('category', models.IntegerField(choices=[(1, '食事券'), (2, '商品券'), (3, '金券・クオカ'), (4, '商品'), (9, 'その他')], verbose_name='優待カテゴリ')),
                ('arrival_date', models.DateField(verbose_name='優待到着日')),
                ('timing', models.PositiveSmallIntegerField(choices=[(1, '早い'), (2, '遅い'), (3, '普通'), (9, 'その他')], verbose_name='取得タイミング')),
                ('memo', models.TextField(max_length=2000, verbose_name='メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
            ],
        ),
    ]
