# Generated by Django 5.1.5 on 2025-02-15 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='quantity',
            field=models.PositiveSmallIntegerField(choices=[(100, '100'), (200, '200'), (300, '300'), (400, '400'), (500, '500'), (600, '600'), (700, '700'), (800, '800'), (900, '900'), (1000, '1000')], default=100, verbose_name='株数'),
        ),
    ]
