# Generated by Django 5.1.5 on 2025-02-16 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_record_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='arrival_date',
            field=models.DateField(blank=True, null=True, verbose_name='優待到着日'),
        ),
        migrations.AlterField(
            model_name='record',
            name='fee',
            field=models.IntegerField(blank=True, null=True, verbose_name='手数料'),
        ),
        migrations.AlterField(
            model_name='record',
            name='get_date',
            field=models.DateField(blank=True, null=True, verbose_name='取得日'),
        ),
        migrations.AlterField(
            model_name='record',
            name='memo',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='メモ'),
        ),
        migrations.AlterField(
            model_name='record',
            name='stock_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='株価'),
        ),
        migrations.AlterField(
            model_name='record',
            name='timing',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '早い'), (2, '遅い'), (3, '普通'), (9, 'その他')], null=True, verbose_name='取得タイミング'),
        ),
    ]
