# Generated by Django 5.1.5 on 2025-02-16 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_alter_record_arrival_date_alter_record_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='rank',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '★'), (2, '★★'), (3, '★★★')], null=True, verbose_name='ランク'),
        ),
    ]
