# Generated by Django 5.1.5 on 2025-02-16 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_record_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='detail',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='優待内容'),
        ),
    ]
